stages:
  - init
  - test

lint:
  stage: init
  script:
    - flake8
    - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" --fail-under 50 mmdet


build:
  stage: init
  script:
    - python setup.py check -m -s
    - python -m pip install -e .

unit-test:
  stage: test
  script:
    - python -m coverage run --branch --source mmseg -m pytest tests/
    - python -m coverage xml
    - python -m coverage report -m
  coverage: '/TOTAL.*\s([.\d]+)%/'

integration-test:
  stage: test
  script:
    - echo "[WIP] This job examines integration tests (typically Kneron's)."
